apiVersion: batch/v1
kind: Job
metadata:
  name: bsc-cf-job
spec:
  template:
    spec:
      containers:
      - name: bsc-cf-job
        image: yash5090/bsc-cf:latest
        ports:
        - containerPort: 5000
      restartPolicy: OnFailure
